#base image
FROM ubuntu:24.04

#update and install required packages- gcc and make
RUN apt-get update && apt-get install -y gcc make libssl-dev

#Copy both versions of the library
COPY mta-utils-dev-aarch64.deb /tmp/

# Install the correct version of the library depending on the architecture
RUN dpkg -i /tmp/mta-utils-dev-aarch64.deb || true

# Fix any missing dependencies (in case the .deb missed something)
RUN apt-get install -f -y

#ensure that the /var/log directory exists
RUN mkdir -p /var/log

#set the working directory inside the container to /app
WORKDIR /app

#copy source and header files into the containers /app directory
COPY decrypt.c decrypt_funcs.c config.c config.h decrypt_funcs.h ./

#compile the decrypter program
RUN gcc -o decrypter decrypt.c decrypt_funcs.c config.c -lpthread -lmta_crypt -lmta_rand -lcrypto

#set the default command to run the decrypter executable
CMD ["./decrypter"]
