#base image
FROM ubuntu:24.04

#Argument for architecture (default is amd64)
ARG ARCH=amd64

#update and install required packages- gcc and make
RUN apt-get update && apt-get install -y gcc make libssl-dev

#Copy both versions of the library
COPY mta-utils-dev-x86_64.deb /tmp/
COPY mta-utils-dev-aarch64.deb /tmp/

# Install the correct version of the library depending on the architecture
RUN if [ "$ARCH" = "arm64" ]; then \
      dpkg -i /tmp/mta-utils-dev-aarch64.deb; \
    else \
      dpkg -i /tmp/mta-utils-dev-x86_64.deb; \
    fi
    
#ensure that the /var/log directory exists
RUN mkdir -p /var/log

#set the working directory inside the container to /app
WORKDIR /app

#copy source and header files into the containers /app directory
COPY encrypt.c encrypt_funcs.c config.c config.h encrypt_funcs.h ./

#compile the encrypter program
RUN gcc -o encrypter encrypt.c encrypt_funcs.c config.c -lpthread -lmta_crypt -lmta_rand -lcrypto

#set the default command to run the encrypter executable
CMD ["./encrypter"]
